version: '3.7'

services:
  easy_team-postgres:
    image: postgres:latest
    container_name: easy_team_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - custom_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: easy_team_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - easy_team-postgres
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
